name: ci
on:
  push:
  pull_request:
  schedule:
  - cron:  '0 3 * * 6' # 3am Saturday
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['9.8', '9.6', '9.4']
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
    - run: cabal new-build all
    - run: cabal new-test --test-option=--color=always --test-show-details=always test:placeholder-test
